### ISSUE TITLE
defaultHandler doesn't support array fields

### ISSUE THREAD

**Issue by bradchoate** [codeledge/ra-data-simple-prisma#34]
MongoDB has support for array fields, but the defaultHandler presumes an array value is only used for updating foreign key relationships. I would just recommend doing something like this for the array case:

```
if (foreignConnectKey) {
    ...existing code...
} else {
    fields[key] = value;
}
```

**Comment by martin-fv** [comment]
Yes, we will work on it soon. Meanwhile free free to open a PR.
