### ISSUE TITLE
findMany variant handlers should support options parameter

### ISSUE THREAD

**Issue by bradchoate** [codeledge/ra-data-simple-prisma#39]
I'd like to have the option to use the `include` property for Prisma's `findMany` call that is used by the `getMany` and `getManyReference` API handlers. Both of these handlers should support the same set of options that are supported for the `getList` API handler.

**Comment by ogroppo** [comment]
Hey @bradchoate - you mean this right? https://github.com/codeledge/ra-data-simple-prisma/pull/40/files
Apologies if it hasn't been done for all methods, if you'd like to apply the same change to `getManyReference` I can merge both today

**Comment by bradchoate** [comment]
Yep, that looks good to me. Thanks!

**Comment by ogroppo** [comment]
Hi @bradchoate, could you give a go to ra-data-simple-prisma@1.1.5 fixed by https://github.com/codeledge/ra-data-simple-prisma/pull/40

**Comment by bradchoate** [comment]
Verified fixed. Thanks!

**Comment by bradchoate** [comment]
Oops... just realized I was still using my customized handler and not the new released code. It appears that the defaultHandler implementation is not passing `options?.getMany` and `options?.getManyReference` to the respective handlers (line ~58 and ~61 respectively).

**Comment by ogroppo** [comment]
Apologies, this change was actually in another PR. published `ra-data-simple-prisma@2.0.0` (note the filter mode i.e. "insensitive", needs to be explicitly passed as not all DBs are supporting it)

**Comment by bradchoate** [comment]
Thanks! Just verified the 2.0.0 release is working properly for supplying custom options for these handlers.
