### ISSUE TITLE
Remix Examples

### ISSUE THREAD

**Issue by moishinetzer** [codeledge/ra-data-simple-prisma#46]
You say that this can work with any node-based backend. However, it seems the whole implementation is based on next.js request handlers. Could you please provide an example for remix? Thanks!

**Comment by ogroppo** [comment]
Hi @moishinetzer, actually only the examples are in next but it's not really coupled to that... I am not familiar with remix but I am looking at the docs right now, it seems there isn't the concept of response object? (request instead is the first parameter of the API route function).
So I guess the only problem would be the `res.json` that in Remix is just `json`... interesting

**Comment by moishinetzer** [comment]
Yes exactly, and also the Request has a different type signature for some reason?

**Comment by ogroppo** [comment]
uuuh just saw this in remix docs `const body = await request.formData();` - I'm afraid remix have gone down a different route to the point it's not compatible with traditional request/response objects.
Given the low support requests for remix I don't think we are able to accommodate this, will mention in readme, sorry!

**Comment by matt-winfield** [comment]
I've been experimenting with this, and it seems to work fine with Remix. You need to expose resource route using a file called `api.$.tsx` (if using flat routes), and then set your file contents like this:

```
import { prisma } from '../your/prisma/client.tsx';
import { json, type DataFunctionArgs } from '@remix-run/server-runtime';
import { defaultHandler, type RaPayload } from 'ra-data-simple-prisma';

export const loader = async ({ request }: DataFunctionArgs) => {
    const body = (await request.json()) as RaPayload;

    const result = await defaultHandler(body, prisma);
    return json(result);
};

export const action = loader;
```

This seems to behave as expected.

**Comment by ogroppo** [comment]
Hi @matt-winfield, indeed - From version 3 it's completely up to the framework to send the response (and to get the body accordingly), so any backend would work really... Thanks for the example tho, I will add it to readme!

**Comment by justin-hackin** [comment]
> request.json(

This seems to breaks the route because the GET request doesn't have a body and so you end up with `Unexpected end of JSON input` on the call to `await request.body()`
