### ISSUE TITLE
Update extractWhere.ts

### ISSUE THREAD

**Issue by linsua01** [codeledge/ra-data-simple-prisma#50]
Hi, 
I started working with ra-data-simple-prisma a time ago, it's very cool solution, thank you a lot!

I found an issue with the filter (where), as I been saw, It's is no posible to search for more than 1 column on each text input,

I find a solution, I would love to shere with you, would be great to know what do you think  :)

passing a string with separate ',' for each column and ':' for the related fields
```
const profileFilters = [
  <TextInput key="1" label="Smart Search" source="firstName,lastName,idNumber,user:email" alwaysOn resettable={true}/>
];
```

```
const userFilters = [
  <TextInput key="1" label="Smart Search" source="name,email,companies:some:name" alwaysOn />,
];
```

in the extractWhere.ts

```
 if (colName.includes(",") || colName.includes(":")) {
        const colsName = colName.split(",");
        auxWhere = colsName.map((colName, i) => {
          const aux = {}
          setObjectProp(aux, colName.replaceAll(':','.'), {
            contains: value,
            mode: options?.filterMode ? options?.filterMode : "insensitive",
          });
          return {...aux}
        });
        setObjectProp(where, 'OR', auxWhere)
        return;
      }


```

**Comment by ogroppo** [comment]
Hi Luciano, it's a creative idea indeed, but it would have the following problems:
- Tie react admin to the custom data provider (the syntax with commas and colon will not be compatible with other dataproviders)
- Potentially go in infinite combinations of related fields (and inevitably tie the syntax to prisma with "some" for instance)

What I suggest is just to use a private field i.e. `<TextInput source="_smart_search" />` the underscore will be ignored, but you can still catch it (with the relevant handler) and do what you want on the server!
