### ISSUE TITLE
Transform may not working

### ISSUE THREAD

**Issue by Lagyu** [codeledge/ra-data-simple-prisma#53]
I wanted to use `_id` field as id, so I wrote this. (I also had to remove "id" from orderBy tbh.)

```typescript
import { defaultHandler, getListHandler } from 'ra-data-simple-prisma';
import { NextApiRequest, NextApiResponse } from 'next';
import { PrismaClient } from '@prisma/client';
import { retrieveDatabaseUrl } from '../../src/logic/retrieveDatabaseUrl';

const handler = async (req: NextApiRequest, res: NextApiResponse) => {
  if (!process.env['DATABASE_URL']) {
    process.env['DATABASE_URL'] = await retrieveDatabaseUrl();
  }
  const prismaClient = new PrismaClient();
  switch (req.body.method) {
    case 'getList':
      return getListHandler(req, res, prismaClient.user, {
        transform: (data: Array<any>) => {
          return data.map((entry) => ({
            ...entry,
            id: Object.entries(entry).find(([key]) => key === '_id')?.[1],
          }));
        },
      });
    default:
      return defaultHandler(req, res, prismaClient);
  }
};

export default handler;
```

However, this gives me an error,
`The response to 'getList' must be like { data : [{ id: 123, ...}, ...] }, but the received data items do not have an 'id' key. The dataProvider is probably wrong for 'getList'`.

Is transform working as intended?
Or should I use something other than transform?

**Comment by ogroppo** [comment]
Hi, yes transform is a good solution, however I don't fully understand why implementing it as `id: Object.entries(entry).find(([key]) => key === '_id')?.[1],`
I imagine it would be something like 
```
transform: (data: Array<any>) => {
          return data.map((entry) => ({
            ...entry,
            id: entry._id,
          }));
        },
``` 

no?

**Comment by Lagyu** [comment]
Thank you for reply.
Oh, yes, I was crazy. I will write as you say.

Anyway, after the edit, I cannot make my react-admin work.
It seems transform is not applied to api output.

**Comment by ogroppo** [comment]
If you have other questions you would like to solve please open a new issue.

Also, I do not recommend instantiating a prisma client on every request, better to isolate it in a file, example here:

https://github.com/codeledge/ra-data-simple-prisma/blob/main/packages/db/prisma/prismaClient.ts
