### ISSUE TITLE
Problem occurs when trying to clone the record.

### ISSUE THREAD

**Issue by Frostbourn** [codeledge/ra-data-simple-prisma#61]
Hi

Thank you for your work! I just want to report that I added CloneButton component in the List DataGrid and got following error while trying to copy record:

```
/app/node_modules/ra-data-simple-prisma/dist/index.js:606:27
603 const where = { id };
604 if (options == null ? void 0 : options.debug)
605   console.log("getOneHandler:where", where);
606 const row = await model.findUnique({
         where: {
             id: 'create'
                    ~~~~~~~~
         },
        select: undefined,
         include: undefined
      })

Argument id: Got invalid value 'create' on prisma.findUniquePage. Provided String, expected Int.

```

**Comment by ogroppo** [comment]
Hi There! Good shout - I will add the clone button to the demo app and add this capability 👍

**Comment by ogroppo** [comment]
Mmh, I had a look but the button is just pre-filling a create form, which is not sending up any `id` field.

Could you provide more info around how to reproduce this?

**Comment by ogroppo** [comment]
Closing this as I am not sure I understand the issue
