### ISSUE TITLE
How to set withCredential in Axios ?

### ISSUE THREAD

**Issue by alexandre-dos-reis** [codeledge/ra-data-simple-prisma#63]
Hi, thank you for this project 👍🏼. 

I would like to pass httpOnly cookies on every subsequent requests. With Axios, it seems that it is possible with the `axios.create()` method, like so:

```js
const instance = axios.create({
   withCredentials: true,
   baseURL: BASE_URL
})
```

However, in your package it seems unreachable:

https://github.com/codeledge/ra-data-simple-prisma/blob/8d4ae431e5074439571aeecc9e2046270be9a2a2/packages/ra-data-simple-prisma/src/dataProvider.ts#L32-L35

Any solution ?

**Comment by ogroppo** [comment]
Could you try version `2.3.1`, added the `withCredentials` optional option :)

**Comment by alexandre-dos-reis** [comment]
Thank you. I don't know if it works, because I'm trying to use cross-domain cookies between the api and the react-admin app, and HTTPS is mandatory. (I need to set a dev server with https like caddy, etc...).

Another thing, as I was using an early version of your package, axios got bumped to 1.4.0 version. Now I'm getting error in the headers definitions:

<img width="1121" alt="Capture d’écran 2023-06-06 à 10 17 41" src="https://github.com/codeledge/ra-data-simple-prisma/assets/54753383/68c538eb-21d3-4a0f-9db9-3087a51e7e4f">

I guess it's axios fault...

**Comment by ogroppo** [comment]
Hi Alexandre - I've updated the headers type to pick from what the library uses to create the axios instance.

Could you give a go at version `2.3.2` and let me know if that works for you?

**Comment by alexandre-dos-reis** [comment]
This fixes the error thank you !

**Comment by alexandre-dos-reis** [comment]
`withCredentials` is working ! Thank you for your work and time !
