### ISSUE TITLE
Return mapped data instead of transform

### ISSUE THREAD

**Issue by ogroppo** [codeledge/ra-data-simple-prisma#64]
`await options?.transform?.(data);` => `mappedData = await options?.mapData.(data);`

**Comment by gauthierm** [comment]
This is in the context of `getOneHandler`.

The `getListHandler` already supports a `map` option but it confusingly does not map the data. For `getOne` a map operation does not make sense as it's only transforming the current row, so the proposed name in this issue does not make sense.

For backwards compatibility you could make the existing transform optional optionally return a value. This will allow a mutator transform to continue to work, as well as allowing a pure transform function:

```ts
// getOneHandler.ts

const transformedRow = await options?.transform?.(row) ?? row;
```

This improvement to getListHandler would also allow you to pass the _same_ transformer function into both `getOneHandler` and `getListHandler`. This would be a great improvement:

```ts
// getListHandler.ts

const transformedData = options?.transformRow
  ? await Promise.all(data.map(options.transformRow))
  : data;
```

With these changes you could write a resource handler that does computed fields like this:

```ts

function addFullName(row: User) {
  return {
    ...row,
    fullName: `${row.firstName} ${row.lastName}`
  };
}

const responseData = await defaultHandler(request, client, {
  getList: {
    transformRow: addFullName
  },
  getOne: {
    transform: addFullName
  }
});

**Comment by ogroppo** [comment]
You raised a very good point sir, what do you think about adding `mapRow` to both getList and getOne? https://github.com/codeledge/ra-data-simple-prisma/pull/77/files

**Comment by gauthierm** [comment]
I like the idea of adding an option (or modifying existing options) to both `getOneHandler` and `getListHandler` so you can pass a single-row transform function of he form `(row) => newModifiedRow`.

I'm not sure the name `mapRow` makes sense for `getOneHandler` since a map operation is usually performed on an collection instead of a single item.

The name `transform` makes the most sense for `getOneHandler`. I think the changes I proposed in my comment would allow existing code to continue to work while also allowing a pure transform function to be used. Would you like a proposed PR?

**Comment by ogroppo** [comment]
Ok, agree on the `transformRow`, however for the `getOneHandler` changing the existing `transform` would break the instances where no record is returned? i.e. quoting your example `const transformedRow = await options?.transform?.(row) ?? row;` this will return undefined.
So perhaps it would be safer to move to a new prop before a major version dropping the old one?

**Comment by gauthierm** [comment]
I _think_ that code is backwards compatible. Here's an example you can run in a console:

```ts
// mutator transform that returns void and modifies the input object, returns modified row
const options1 = { transform: (row) => { row.newField = 'test'; }};
const row1 = { existingField: 'foo' };
const transformedRow1 = await options1?.transform?.(row1) ?? row1;

// no transformer, returns existing row
const options2 = { };
const row2 = { existingField: 'foo' };
const transformedRow2 = await options2?.transform?.(row2) ?? row2;

// pure transform function that returns a new object, returns new row
const options3 = { transform: (row) => ({ ...row, newField: 'test' }) };
const row3 = { existingField: 'foo' };
const transformedRow3 = await options3?.transform?.(row3) ?? row3;

console.log(transformedRow1);
console.log(transformedRow2);
console.log(transformedRow3);
```

**Comment by gauthierm** [comment]
The one instance where this could cause issues is if you want to write a transformer that turns a row into undefined. I'm not sure if that is a problem:

```ts
// transforms row into undefined, this may unexpectedly return the original row
const options4 = { transform: (row) => undefined };
const row4 = { existingField: 'foo' };
const transformedRow4 = await options4?.transform?.(row4) ?? row4;
```

**Comment by ogroppo** [comment]
Alright, I'll update the PR with `transform` and `transformRow` 👍🏻

**Comment by ogroppo** [comment]
Hi, I'm not convinced about this case:
```
// no transformer, returns existing row
const options2 = { };
const row2 = { existingField: 'foo' };
const transformedRow2 = await options2?.transform?.(row2) ?? row2;
```
The return value of the modifier function is always undefined, so it will be always `?? row2`

**Comment by gauthierm** [comment]
In this case, `options2?.transform` is undefined so it will not try to run the function and will return the default value of `row2`.

In the case where you want a modifier transform function, the function is defined and runs, but the result is undefined so you get the default value (which was modified by the function).

**Comment by ogroppo** [comment]
Hi, I believe you're missing the point that even if the function is defined people using it a a transformer currently return void so the output will always be assigned to `row2` (`void ?? row2 => row2`) i.e. being a breaking change... It needs to be a new prop am afraid.
Leaving issue open until new prop name has been decided (`mapData` `mapRow` or `transformRow`)

**Comment by gauthierm** [comment]
> Hi, I believe you're missing the point that even if the function is defined people using it a a transformer currently return void so the output will always be assigned to row2 (void ?? row2 => row2) i.e. being a breaking change... It needs to be a new prop am afraid.

Existing transform functions are mutation functions that change the properties of row2 and return void. When the transform returns void and nullish coalescing is applied, it gives you row2, which was mutated by the transform function.

I'm perhaps being too fancy compressing this into a single JavaScript expression. You could consider it as:

```ts
let newRow = row;

if (options?.transform) {
  const transformedRow = await options.transform(row);
  if (transformedRow) {
    newRow = transformedRow;
  }
}
```

This is the equivalent of what I proposed.

**Comment by ogroppo** [comment]
Hi, thanks for getting back - I understand where you're coming from, however the purpose of this issue was to move away from mutations as they keep being a headache, so adding complexity for compatibility might not be worthwhile.
If you're so keen to use `transform` I can bump the major version, and we get rid of mutations altogether?

**Comment by ogroppo** [comment]
This has been published as a breaking change:
transform on getOne and transformRow on the other methods
`ra-data-simple-prisma@4.0.1`
