### ISSUE TITLE
Problem with updateHandler not converting to connect

### ISSUE THREAD

**Issue by CBrian04** [codeledge/ra-data-simple-prisma#67]
Hi!

First thank you very much for your work! 

I got some issue connecting some elements to another one in an implicit many to many relationship : 
I can't understand the comment on lince 70 in updateHandler.js file : 
`// transform an array to a connect (many-to-many)`
Because just after that you put a "set" with the following code : 
` fields[key] = {
  set: (value as number[]).map((value) => ({
    [foreignSet]: value,
  })),
};`
which is making my prisma update call failing. It works perfectly locally replacing "set" by "connect". 
Am I missing some point or it is a mistake on your side ? I precise that I am on version 2.3.2 (latest at write time)

Thank you.
Have a nice day!
Brian

**Comment by ogroppo** [comment]
Hi @CBrian04 - what kind of error do you get with the `set`? The reason why that is a set is because with a connect you wouldn't be able to remove (or disconnect) the ids not on the list, ie for the classic multi input "tags" field, when you remove a tag you also expect the relationship to be disconnected?

**Comment by CBrian04** [comment]
Really Sorry to have bothering you for nothing it was my bad I corrected my mistake. I thought it was about the connect vs set choice but not at all it was some nextjs issue a little bit further in code.
I put it here if another people is interested by the issue : passing the basic res object in some handler is not ok because the json function doesn't exist on it, if some people had same problem you have to give NextResponse as arg instead of  it. And you also have to wrap the body of the request in an object, I give here the code for the default handler but the same is done for overriden handlers : 

```
import { defaultHandler } from "ra-data-simple-prisma";
import prisma from "@/lib/prisma";
import { NextResponse } from "next/server";

const handler = async (req: Request, res: Response) => {
  const body = await req.json();
  const handleRes = await defaultHandler({ body }, NextResponse, prisma);
  return NextResponse.json(handleRes);
`};`

export { handler as GET, handler as POST, handler as PUT, handler as DELETE};
```

**Comment by ogroppo** [comment]
Great to hear you got to the bottom of it! and yeah I will update the examples for the app router as it has been flagged already.
