### ISSUE TITLE
Type for GetListRequest is incorrect

### ISSUE THREAD

**Issue by gauthierm** [codeledge/ra-data-simple-prisma#72]
This type expects a top-level `filter` as well as a `filter` in the params. React Admin only sends the filter in params like:

```ts
{
  method: 'getList',
  resource: 'posts',
  params: {
    pagination: {
      page: 1,
      perPage: 10
    },
    sort: {
      field: 'id',
      order: 'ASC'
    },
    filter: {}
  }
}
```

The top-level `filter` property should be removed so type checks work properly.

**Comment by ogroppo** [comment]
Good shout, removing now!

**Comment by ogroppo** [comment]
Removed in ra-data-simple-prisma@3.1.2
