### ISSUE TITLE
Error handling is incorrect

### ISSUE THREAD

**Issue by gauthierm** [codeledge/ra-data-simple-prisma#73]
React Admin describes how to handle errors in https://marmelab.com/react-admin/DataProviderWriting.html#error-format

There is an existing error class defined in React Admin specifically for this called `HttpError`. In this adapter, the error handler is throwing strings rather than error objects with a status field. It should be updated to throw instances of HttpError.

**Comment by ogroppo** [comment]
Fixed in `ra-data-simple-prisma@3.1.2` - backend will need to put the error message inside the `message` prop of the response, seems ra also accepts somehow the error stack so it can preview it in dev mode but haven't figured out it yet
