### ISSUE TITLE
Support for string_contains for pgjson filter

### ISSUE THREAD

**Issue by CBrian04** [codeledge/ra-data-simple-prisma#88]
Hi!

Firstly I would like to thank you for the recent _pgjson filter implementation!
Do you plan to go little further with string_contains filter in addition to the "equals" filter already implemented ? (and maybe startWith and endWith but less important).

Have a nice day!
Brian

**Comment by orlando-fv** [comment]
Hi Brian, yes `contains` `startsWith` and `endsWith` are already implemented (note is called ends with s) - check docs [here](https://github.com/codeledge/ra-data-simple-prisma/blob/main/packages/ra-data-simple-prisma/README.md) 
<img width="572" alt="Screenshot 2024-06-18 at 21 18 24" src="https://github.com/codeledge/ra-data-simple-prisma/assets/75616282/123de998-9731-465d-be1c-81048fcf4565">

**Comment by ogroppo** [comment]
C
