### ISSUE TITLE
First page with 1000 records causes no limit

### ISSUE THREAD

**Issue by richarpw** [codeledge/ra-data-simple-prisma#89]
I am trying to understand the [following code](https://github.com/codeledge/ra-tools/blob/ed7ce09a92a2166ef1eb0f81b7fb8703fcc534ac/packages/ra-data-simple-prisma/src/extractSkipTake.ts#L17). If you set your pagination to 1000 the getList call with have no limit, which is not desired if the database has millions of records.

  params: {
    pagination: { page: 1, perPage: 1000 },
  },

**Comment by ogroppo** [comment]
Hi @richarpw - this is because the export button is calling the backend with no other parameters that suggest it's an export operation. It's more a workaround than anything.

**Comment by richarpw** [comment]
How can I make it so when calling, the paging is as above but it isn't an export, but to return the list with 1000 results for the first page?

**Comment by ogroppo** [comment]
Hi @richarpw - yeah sadly you'd need to choose a different number as page size (900, 1001?) that's a custom parameter passed to the paginator options anyway. If you find a way I'm happy to integrate but so far it is what it is...
