### ISSUE TITLE
Add support for select distinct in getList

### ISSUE THREAD

**Issue by CBrian04** [codeledge/ra-data-simple-prisma#91]
Hi,

I'm facing a situation where I would need to use the "select distinct" feature from Prisma in a getList (not real postgres distinct but a prisma one which is more compatible). Here a prisma example : 

`const result = await prisma.user.findMany({
  where: {},
  distinct: ['name'],
})`

I am often rewriting some of the different dataProvider methods to add some params or change body before calling it. Here i would like to add a small "distinct" in options but it is not possible with the current getListHandler (I had look at the code). 
If you think that it would be useful for others could you add it?

Have a nice day!
Brian

**Comment by ogroppo** [comment]
Hi @CBrian04 - that's a great shout actually. but I believe prisma returns random rows with the distinct value. What's your use-case, showing single distinct value on a table? (pagination might also behave funny)

**Comment by CBrian04** [comment]
Hi!
My use case is maybe not that common. 
I have a website generator specialized in a particular field where administrators have to be able to rewrite the default labels displayed on their website.
 So I have a "Label" model with a "variable" column and a "custom" column that is false for the default label and true if administrator had overwritten it. If two rows exists  (one with custom to false and the other with custom to true) I need to take the custom one.
 That is why it would be convenient to sort by custom field (true first) et use a select distinct on "variable" column.
 
I have a workaround that work pretty well, calling two times the getList handler, so it is not a necessity for me but I was just wondering if it would be useful to add it to that library without having the answer. If you think that is pertinent it could be added. Else no problem for closing the issue.

Have a nice day!

**Comment by orlando-fv** [comment]
Hey, interesting project, do you have a public url to check? 
Ok, yeah I see what you mean, I have the feeling it's not a feature in the scope of the package, sorry 🙏

**Comment by CBrian04** [comment]
Yes, this is not open source so i just can give you the url of the demo site launched with the generator : 
[https://demo.mon-trail.fr](https://demo.mon-trail.fr)

This is a trail running event website generator developed with NextJs (interesting because 3000 events in France each year, 10% of correct websites, 50% not far from pure html/css website, even for big events)

The project is also interesting in terms of development, there is only one administration dashboard on https://www.mon-trail.fr/espace-administration where different events organizators can log in, modify their website, and push modifications (because static websites this is not done automatically).
And I have only one frontend codebase which take admin data + configuration and generate almost full static website. I use vercel stack everywhere (postgres, vercel blob, hosting, etc), not the cheapest, but it allows be to develop everything on my own.
My only problem is the limit of 60 projects per github repo on vercel.
Everything works pretty well and I am launching the project with 3 organizators next month, before going on the commercial phase. 

The dataprovider that you have developed and maintain help me a lot so thank you for that. As I use it quite intensively, I would probably try to help on some feature when my project will be more stable as I have a tons of things to do now.

Have a nice day!
Brian

**Comment by ogroppo** [comment]
Awesome stuff! what package are you using to authenticate users on the admin route? 

And yeah, of course, contributions are very welcome 🚀 

I am closing the issue now, but you can keep posting updates here if you like 👍🏻

**Comment by CBrian04** [comment]
Thanks!

I'm using NextAuth with a quite simple custom react admin AuthProvider, and store organizationId in session so I can check from which organization request comes from in each api route and check their authorizations.
